# Sistemas de ecuaciones lineales algebraicas

Un sistema de $n$ ecuaciones lineales con $n$ incognitas tiene la forma 
$$\left\{\begin{array}{cc}
a_{11}x_1 + a_{12}x_1 + a_{13}x_1 + \ldots + a_{1n}x_n & = b_1\\
a_{21}x_1 + a_{22}x_1 + a_{23}x_1 + \ldots + a_{2n}x_n & = b_2\\
\vdots & \vdots\\
a_{n1}x_1 + a_{n2}x_1 + a_{n3}x_1 + \ldots + a_{nn}x_n & = b_n\\
\end{array}\right.$$
donde se conocen los coeficientes $a_{ij}$ y las constantes $b_i$, y $x_i$ representan las incognitas. En notación matricial las ecuaciones se escribe como 
$$\begin{bmatrix}
a_{11} & a_{12} & a_{13} & \ldots & a_{1n}\\
a_{21} & a_{22} & a_{23} & \ldots & a_{2n}\\
\vdots & \vdots\\
a_{n1} & a_{n2} & a_{n3} & \ldots & a_{nn}\\
\end{bmatrix} \cdot 
\begin{bmatrix}
x_{1}\\
x_{2}\\
\vdots\\
x_{n}\\
\end{bmatrix} = 
\begin{bmatrix}
b_{1}\\
b_{2}\\
\vdots\\
b_{n}\\
\end{bmatrix}
$$
y si denotamos por $\mathbf{A}$ a la matriz de coeficintes, $\mathbf{x}$ al vector columna de incognita y $\mathbf{b}$ al vector columna de resultados, entonces sistema equiva a la operación $$\mathbf{A} \cdot \mathbf{x} = \mathbf{b}$$


$$\left[A|b\right] = \left[\begin{array}{ccccc|c}
a_{11} & a_{12} & a_{13} & \ldots & a_{1n} & b_1\\
a_{21} & a_{22} & a_{23} & \ldots & a_{2n} & b_2\\
\vdots & \vdots\\
a_{n1} & a_{n2} & a_{n3} & \ldots & a_{nn} & b_n\\
\end{array}\right]$$

## Escribir conceptos basicos de las operaciones con matrices

# Método de Eliminación Gaussiana

Supongamos que tenemos un sistema de ecuaciones lineales de la forma $A \mathbf{x} = \mathbf{b}$, donde $A$ es una matriz de coeficientes $n \times n$, $\mathbf{x}$ es un vector de incógnitas, y $\mathbf{b}$ es un vector de términos independientes.

#### Paso 1: Matriz Aumentada
Formamos la matriz aumentada $[A | \mathbf{b}]$.

#### Paso 2: Eliminación hacia adelante
Convertimos la matriz aumentada en una matriz triangular superior.

1. **Para cada fila $k$ desde 1 hasta $n-1$**:
   - Seleccionamos el pivote $a_{kk}$. Si $a_{kk} = 0$, intercambiamos filas para obtener un pivote no cero.
   - **Para cada fila $i$ desde $k+1$ hasta $n$**:
     - Calculamos el multiplicador $m_{ik} = \dfrac{a_{ik}}{a_{kk}}$.
     - Restamos $m_{ik} \cdot$ (fila $k$) de la fila $i$ para hacer cero los elementos debajo del pivote.

#### Paso 3: Sustitución hacia atrás
Resolvemos el sistema triangular superior resultante.

1. **Para $i$ desde $n$ hasta 1**:
   - $\displaystyle x_i = \frac{b_i - \sum_{j=i+1}^{n} a_{ij} x_j}{a_{ii}}$



## Implementación del metodo 

In [1]:
import numpy as np
# Ejemplo
A = np.array([
     [1,1,0,3],
     [2,1,-1,1],
     [3,-1,-1,2],
     [-1,2,3,-1]
])
b = np.array([4,1,-3,4])

print("A=\n",A)
print("b=\n",b)



A=
 [[ 1  1  0  3]
 [ 2  1 -1  1]
 [ 3 -1 -1  2]
 [-1  2  3 -1]]
b=
 [ 4  1 -3  4]


## Operaciones elementales con renglones

In [2]:
#Intercambio de renglones
A1 = A.copy()
A1[[0,1]]=A1[[1,0]]
print(A1)

[[ 2  1 -1  1]
 [ 1  1  0  3]
 [ 3 -1 -1  2]
 [-1  2  3 -1]]


In [3]:
# Multiplicación de un renglón por escalar
print(5*A[0])

[ 5  5  0 15]


In [4]:
A[1]+A[3]

array([1, 3, 2, 0])

## Matriz Aumentada

In [5]:
b1 = b.reshape(-1,1)
np.hstack([A,b1])

array([[ 1,  1,  0,  3,  4],
       [ 2,  1, -1,  1,  1],
       [ 3, -1, -1,  2, -3],
       [-1,  2,  3, -1,  4]])

## Sustitución inversa

#### Paso 3: Sustitución hacia atrás
Resolvemos el sistema triangular superior resultante.

1. **Para $i$ desde $n$ hasta 1**:
   - $\displaystyle x_i = \frac{b_i - \sum_{j=i+1}^{n} a_{ij} x_j}{a_{ii}}$


In [6]:
def sustInversa(matrizA,vectorb):
    m = len(matrizA) #renglones  
    x = np.zeros(m)

    x[m-1] = vectorb[m-1]/matrizA[m-1][m-1]
    for i in range(m-2,-1,-1):
        suma=0
        for j in range(i+1,m):
            suma +=  matrizA[i][j]*x[j]
        x[i] = (vectorb[i] - suma) / matrizA[i][i]

    return x

In [7]:
# Metodo de Gauss
def metodoGauss(matrizA,vectorb):   
   m = len(matrizA)
   matriz1 = matrizA.copy()
   vectorb1 = vectorb.copy()

   for j in range(m):
      if(matriz1[j][j]==0):
        i=j
        while(matriz1[i][j]==0 and i < m-1):
         i=i+1
        if i == m-1:
            print("El sistema no tiene solución única o no tiene solución")
            break
        else:
           matriz1[[j,i]]=matriz1[[i,j]]
           vectorb1[[j,i]]=vectorb1[[i,j]]
        
      for i in range(j+1,m):
        factor = matriz1[i][j]/matriz1[j][j]
        matriz1[i]= -factor*matriz1[j] + matriz1[i]
        vectorb1[i]= -factor*vectorb1[j] + vectorb1[i]

   y = sustInversa(matriz1,vectorb1)   
   return y

print("LA SOLUCIÓN ES:")    
x = metodoGauss(A,b)
print(x)

    

LA SOLUCIÓN ES:
[-1.  2.  0.  1.]


In [8]:
A1 = np.array([
    [10, -2, -1, 2, 3, 1, -4, 7],
    [5, 11, 3, 10, -3, 3, 3, -4],
    [7, 12, 1, 5, 3, -12, 2, 3],
    [8, 7, -2, 1, 3, 2, 2, 4],
    [2, -15, -1, 1, 4, -1, 8, 3],
    #[-1, 3, 4, 1, 3, -4, 7, 6],
    [4, 2, 9, 1, 12, -1, 4, 1],
    [-1, 4, -7, -1, 1, 1, -1, -3],
    [-1, 3, 4, 1, 3, -4, 7, 6]
],dtype=float)
b1 = np.array([0,12,-5,3,-25,-26,9,-7],dtype=float)
b2 = np.array([1,1,1,1,1,1,1,-1],dtype=float)

x1 = metodoGauss(A1,b1)
print(x1)

[-1.  1. -1.  1. -1.  1. -1.  1.]


## Factorización LU

In [12]:
def factotizacionLU(matrizA):
   m = len(matrizA)
   n = len(matrizA[0])
   matrizL = np.identity(m)
   matrizU = matrizA.copy()

   for j in range(m):
      if(matrizU[j][j]!=0):
        for i in range(j+1,m):
            multiplicador = matrizU[i][j]/matrizU[j][j]
            matrizL[i][j] = multiplicador
            matrizU[i] = - multiplicador*matrizU[j] + matrizU[i]
      else:
         print("No es posible calcular la factotización LU")
         break
   
   return matrizL, matrizU

np.set_printoptions(precision=10,suppress=True,linewidth=400)
L, U= factotizacionLU(A1)
print("L = \n", L)
print("\n")
print("U = \n",U)


L = 
 [[ 1.            0.            0.            0.            0.            0.            0.            0.          ]
 [ 0.5           1.            0.            0.            0.            0.            0.            0.          ]
 [ 0.7           1.1166666667  1.            0.            0.            0.            0.            0.          ]
 [ 0.8           0.7166666667  1.679245283   1.            0.            0.            0.            0.          ]
 [ 0.2          -1.2166666667 -1.5660377358  0.3832335329  1.            0.            0.            0.          ]
 [ 0.4           0.2333333333 -3.8867924528 -7.1327345309 -0.9219435737  1.            0.            0.          ]
 [-0.1           0.3166666667  3.7169811321  5.375249501   1.4263322884 -0.3675371566  1.            0.          ]
 [-0.1           0.2333333333 -1.3962264151 -2.619760479  -0.35830721    0.3236755818 -0.2611316962  1.          ]]


U = 
 [[ 10.            -2.            -1.             2.             3

## Sustitución directa

In [10]:
def sustDirecta(matrizL,b):
    m=len(matrizL) #renglones
    x = [0]*m    
    x[0] = b[0]/matrizL[0][0]
        
    for i in range(1,m):
        suma=0
        for j in range(i):
            suma = suma + matrizL[i][j]*x[j]
        x[i] = (b[i]-suma)/matrizL[i][i]
    return x

y = sustDirecta(L,b2)
print("y = \n", y)

z=sustInversa(U,y)
print("z = \n",z)
print(np.dot(A1,z))



y = 
 [1.0, 0.5, -0.2583333333333333, 0.2754716981132075, 0.8982035928143716, 2.272204806687566, -0.02485940754995508, -1.07580459130094]
z = 
 [ 0.1407020061 -0.0269321345 -0.1095041575  0.071285079   0.125770605  -0.0121041924  0.0083083184 -0.1492761421]
[ 1.  1.  1.  1.  1.  1.  1. -1.]
